### Send SIGNUP request
POST https://base-api.asapcashier-dev.com/auth/sign-up
Content-Type: application/json

{
  "userName": "dramwork2",
  "password": "dramwork2",
  "email": "dramwork7@gmail.com"
}

### Send LOGIN request
POST https://base-api.asapcashier-dev.com/auth/sign-in
Content-Type: application/json

{
  "email": "f32wwal@tes.com",
  "password": "test123456"
}

### Send LOGIN request
POST https://base-api.asapcashier-dev.com/auth/sign-in
Content-Type: application/json

{
  "email": "alexP@releaseasap.com",
  "password": "test1234"
}
