### Send SIGNUP request
POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
  "userName": "dramwork2",
  "password": "dramwork2",
  "email": "dramwork2@gmail.com"
}

### Send SIGNIN request
POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
  "password": "dramwork",
  "email": "dramwork5@gmail.com"
}
