### Send Save Widget Settings request
POST http://localhost:3000/widget/settings
Content-Type: application/json

{
  "userId": "1",
  "settings": {
    "paymentMethodsViewType": "Basic",
    "layout": "Separate",
    "buttonText": "PAY",
    "colorModeStyles": {
      "dark": {
        "font": "Inter",
        "fontSize": "16",
        "cornerRadius": "7",
        "backgroundColor": "#070707",
        "textColor": "#fcfbfb",
        "fieldColor": "#161616",
        "lineColor": "#282829",
        "iconColor": "#a48ee4",
        "buttonBackgroundColor": "#a48ee4",
        "buttonTextColor": "#FFFFFF"
      },
      "light": {
        "font": "Inter",
        "fontSize": "16",
        "cornerRadius": "7",
        "backgroundColor": "#F6F6F6",
        "textColor": "#000000",
        "fieldColor": "#FFFFFF",
        "lineColor": "#E9E6EF",
        "iconColor": "#4723AD",
        "buttonBackgroundColor": "#4723AD",
        "buttonTextColor": "#FFFFFF"
      }
    }
  }
}

### Send Get Widget Settings request
GET http://localhost:3000/widget/settings?userId=1

### Send Pay request
POST http://localhost:3000/widget/pay
Content-Type: application/json

{
}
